[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
l1 = "http://47.251.56.125:8545/nkuHJISaDZxGhsfoYIzxUUNt/l1"
l2 = "http://47.251.56.125:8545/nkuHJISaDZxGhsfoYIzxUUNt/l2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
